//-------------------------------------------------------------------------
/*
Copyright (c) 2010 - JV Software
Copyright (C) 1996, 2003 - 3D Realms Entertainment

This file is part of the XNA Duke Nukem 3D Atomic Edition Port

Duke Nukem 3D is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
aint with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Original Source: 1996 - Todd Replogle
Prepared for public release: 03/21/2003 - Charlie Wiederhold, 3D Realms
Ported to Silverlight/XNA C# 05/03/2011 - Justin Marshall, JV Software
*/
//-------------------------------------------------------------------------

using System;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;

namespace duke3d.game
{
    public static class SoundId
    {
        public const int KICK_HIT              =           0;
        public const int PISTOL_RICOCHET       =           1;
        public const int PISTOL_BODYHIT        =           2;
        public const int PISTOL_FIRE           =           3;
        public const int EJECT_CLIP            =           4;
        public const int INSERT_CLIP           =           5;
        public const int CHAINGUN_FIRE         =           6;
        public const int RPG_SHOOT             =           7;
        public const int POOLBALLHIT           =           8;
        public const int RPG_EXPLODE           =           9;
        public const int CAT_FIRE              =          10;
        public const int SHRINKER_FIRE         =          11;
        public const int ACTOR_SHRINKING       =          12;
        public const int PIPEBOMB_BOUNCE       =          13;
        public const int PIPEBOMB_EXPLODE      =          14;
        public const int LASERTRIP_ONWALL      =          15;
        public const int LASERTRIP_ARMING      =          16;
        public const int LASERTRIP_EXPLODE     =          17;
        public const int VENT_BUST             =          18;
        public const int GLASS_BREAKING        =          19;
        public const int GLASS_HEAVYBREAK      =          20;
        public const int SHORT_CIRCUIT         =          21;
        public const int ITEM_SPLASH           =          22;
        public const int DUKE_BREATHING        =          23;
        public const int DUKE_EXHALING         =          24;
        public const int DUKE_GASP             =          25;
        public const int SLIM_RECOG            =          26;
        // public const int ENDSEQVOL3SND1     =             27;
        public const int DUKE_URINATE          =          28;
        public const int ENDSEQVOL3SND2        =          29;
        public const int ENDSEQVOL3SND3        =          30;
        public const int DUKE_PASSWIND         =          32;
        public const int DUKE_CRACK            =          33;
        public const int SLIM_ATTACK           =          34;
        public const int SOMETHINGHITFORCE     =          35;
        public const int DUKE_DRINKING         =          36;
        public const int DUKE_KILLED1          =          37;
        public const int DUKE_GRUNT            =          38;
        public const int DUKE_HARTBEAT         =          39;
        public const int DUKE_ONWATER          =          40;
        public const int DUKE_DEAD             =          41;
        public const int DUKE_LAND             =          42;
        public const int DUKE_WALKINDUCTS      =          43;
        public const int DUKE_GLAD             =          44;
        public const int DUKE_YES              =          45;
        public const int DUKE_HEHE             =          46;
        public const int DUKE_SHUCKS           =          47;
        public const int DUKE_UNDERWATER       =          48;
        public const int DUKE_JETPACK_ON       =          49;
        public const int DUKE_JETPACK_IDLE     =          50;
        public const int DUKE_JETPACK_OFF      =          51;
        public const int LIZTROOP_GROWL        =          52;
        public const int LIZTROOP_TALK1        =          53;
        public const int LIZTROOP_TALK2        =          54;
        public const int LIZTROOP_TALK3        =          55;
        public const int DUKETALKTOBOSS        =          56;
        public const int LIZCAPT_GROWL         =          57;
        public const int LIZCAPT_TALK1         =          58;
        public const int LIZCAPT_TALK2         =          59;
        public const int LIZCAPT_TALK3         =          60;
        public const int LIZARD_BEG            =          61;
        public const int LIZARD_PAIN           =          62;
        public const int LIZARD_DEATH          =          63;
        public const int LIZARD_SPIT           =          64;
        public const int DRONE1_HISSRATTLE     =          65;
        public const int DRONE1_HISSSCREECH    =          66;
        public const int DUKE_TIP2             =          67;
        public const int FLESH_BURNING         =          68;
        public const int SQUISHED              =          69;
        public const int TELEPORTER            =          70;
        public const int ELEVATOR_ON           =          71;
        public const int DUKE_KILLED3          =          72;
        public const int ELEVATOR_OFF          =          73;
        public const int DOOR_OPERATE1         =          74;
        public const int SUBWAY                =          75;
        public const int SWITCH_ON             =          76;
        public const int FAN                   =          77;
        public const int DUKE_GETWEAPON3       =          78;
        public const int FLUSH_TOILET          =          79;
        public const int HOVER_CRAFT           =          80;
        public const int EARTHQUAKE            =          81;
        public const int INTRUDER_ALERT        =          82;
        public const int END_OF_LEVEL_WARN     =          83;
        public const int ENGINE_OPERATING      =          84;
        public const int REACTOR_ON            =          85;
        public const int COMPUTER_AMBIENCE     =          86;
        public const int GEARS_GRINDING        =          87;
        public const int BUBBLE_AMBIENCE       =          88;
        public const int MACHINE_AMBIENCE      =          89;
        public const int SEWER_AMBIENCE        =          90;
        public const int WIND_AMBIENCE         =          91;
        public const int SOMETHING_DRIPPING    =          92;
        public const int STEAM_HISSING         =          93;
        public const int THEATER_BREATH        =          94;
        public const int BAR_MUSIC             =          95;
        public const int BOS1_ROAM             =          96;
        public const int BOS1_RECOG            =          97;
        public const int BOS1_ATTACK1          =          98;
        public const int BOS1_PAIN             =          99;
        public const int BOS1_DYING            =         100;
        public const int BOS2_ROAM             =         101;
        public const int BOS2_RECOG            =         102;
        public const int BOS2_ATTACK           =         103;
        public const int BOS2_PAIN             =         104;
        public const int BOS2_DYING            =         105;
        public const int GETATOMICHEALTH       =         106;
        public const int DUKE_GETWEAPON2       =         107;
        public const int BOS3_DYING            =         108;
        public const int SHOTGUN_FIRE          =         109;
        public const int PRED_ROAM             =         110;
        public const int PRED_RECOG            =         111;
        public const int PRED_ATTACK           =         112;
        public const int PRED_PAIN             =         113;
        public const int PRED_DYING            =         114;
        public const int CAPT_ROAM             =         115;
        public const int CAPT_ATTACK           =         116;
        public const int CAPT_RECOG            =         117;
        public const int CAPT_PAIN             =         118;
        public const int CAPT_DYING            =         119;
        public const int PIG_ROAM              =         120;
        public const int PIG_RECOG             =         121;
        public const int PIG_ATTACK            =         122;
        public const int PIG_PAIN              =         123;
        public const int PIG_DYING             =         124;
        public const int RECO_ROAM             =         125;
        public const int RECO_RECOG            =         126;
        public const int RECO_ATTACK           =         127;
        public const int RECO_PAIN             =         128;
        public const int RECO_DYING            =         129;
        public const int DRON_ROAM             =         130;
        public const int DRON_RECOG            =         131;
        public const int DRON_ATTACK1          =         132;
        public const int DRON_PAIN             =         133;
        public const int DRON_DYING            =         134;
        public const int COMM_ROAM             =         135;
        public const int COMM_RECOG            =         136;
        public const int COMM_ATTACK           =         137;
        public const int COMM_PAIN             =         138;
        public const int COMM_DYING            =         139;
        public const int OCTA_ROAM             =         140;
        public const int OCTA_RECOG            =         141;
        public const int OCTA_ATTACK1          =         142;
        public const int OCTA_PAIN             =         143;
        public const int OCTA_DYING            =         144;
        public const int TURR_ROAM             =         145;
        public const int TURR_RECOG            =         146;
        public const int TURR_ATTACK           =         147;
        public const int DUMPSTER_MOVE         =         148;
        public const int SLIM_DYING            =         149;
        public const int BOS3_ROAM             =         150;
        public const int BOS3_RECOG            =         151;
        public const int BOS3_ATTACK1          =         152;
        public const int BOS3_PAIN             =         153;
        public const int BOS1_ATTACK2          =         154;
        public const int COMM_SPIN             =         155;
        public const int BOS1_WALK             =         156;
        public const int DRON_ATTACK2          =         157;
        public const int THUD                  =         158;
        public const int OCTA_ATTACK2          =         159;
        public const int WIERDSHOT_FLY         =         160;
        public const int TURR_PAIN             =         161;
        public const int TURR_DYING            =         162;
        public const int SLIM_ROAM             =         163;
        public const int LADY_SCREAM           =         164;
        public const int DOOR_OPERATE2         =         165;
        public const int DOOR_OPERATE3         =         166;
        public const int DOOR_OPERATE4         =         167;
        public const int BORNTOBEWILDSND       =         168;
        public const int SHOTGUN_COCK          =         169;
        public const int GENERIC_AMBIENCE1     =         170;
        public const int GENERIC_AMBIENCE2     =         171;
        public const int GENERIC_AMBIENCE3     =         172;
        public const int GENERIC_AMBIENCE4     =         173;
        public const int GENERIC_AMBIENCE5     =         174;
        public const int GENERIC_AMBIENCE6     =         175;
        public const int BOS3_ATTACK2          =         176;
        public const int GENERIC_AMBIENCE17    =         177;
        public const int GENERIC_AMBIENCE18    =         178;
        public const int GENERIC_AMBIENCE19    =         179;
        public const int GENERIC_AMBIENCE20    =         180;
        public const int GENERIC_AMBIENCE21    =         181;
        public const int GENERIC_AMBIENCE22    =         182;
        public const int SECRETLEVELSND        =         183;
        public const int GENERIC_AMBIENCE8     =         184;
        public const int GENERIC_AMBIENCE9     =         185;
        public const int GENERIC_AMBIENCE10    =         186;
        public const int GENERIC_AMBIENCE11    =         187;
        public const int GENERIC_AMBIENCE12    =         188;
        public const int GENERIC_AMBIENCE13    =         189;
        public const int GENERIC_AMBIENCE14    =         190;
        public const int GENERIC_AMBIENCE15    =         192;
        public const int GENERIC_AMBIENCE16    =         193;
        public const int FIRE_CRACKLE          =         194;
        public const int BONUS_SPEECH1         =         195;
        public const int BONUS_SPEECH2         =         196;
        public const int BONUS_SPEECH3         =         197;
        public const int PIG_CAPTURE_DUKE      =         198;
        public const int BONUS_SPEECH4         =         199;
        public const int DUKE_LAND_HURT        =         200;
        public const int DUKE_HIT_STRIPPER1    =         201;
        public const int DUKE_TIP1             =         202;
        public const int DUKE_KILLED2          =         203;
        public const int PRED_ROAM2            =         204;
        public const int PIG_ROAM2             =         205;
        public const int DUKE_GETWEAPON1       =         206;
        public const int DUKE_SEARCH2          =         207;
        public const int DUKE_CRACK2           =         208;
        public const int DUKE_SEARCH           =         209;
        public const int DUKE_GET              =         210;
        public const int DUKE_LONGTERM_PAIN    =         211;
        public const int MONITOR_ACTIVE        =         212;
        public const int NITEVISION_ONOFF      =         213;
        public const int DUKE_HIT_STRIPPER2    =         214;
        public const int DUKE_CRACK_FIRST      =         215;
        public const int DUKE_USEMEDKIT        =         216;
        public const int DUKE_TAKEPILLS        =         217;
        public const int DUKE_PISSRELIEF       =         218;
        public const int SELECT_WEAPON         =         219;
        public const int WATER_GURGLE          =         220;
        public const int DUKE_GETWEAPON4       =         221;
        public const int JIBBED_ACTOR1         =         222;
        public const int JIBBED_ACTOR2         =         223;
        public const int JIBBED_ACTOR3         =         224;
        public const int JIBBED_ACTOR4         =         225;
        public const int JIBBED_ACTOR5         =         226;
        public const int JIBBED_ACTOR6         =         227;
        public const int JIBBED_ACTOR7         =         228;
        public const int DUKE_GOTHEALTHATLOW   =         229;
        public const int BOSSTALKTODUKE        =         230;
        public const int WAR_AMBIENCE1         =         231;
        public const int WAR_AMBIENCE2         =         232;
        public const int WAR_AMBIENCE3         =         233;
        public const int WAR_AMBIENCE4         =         234;
        public const int WAR_AMBIENCE5         =         235;
        public const int WAR_AMBIENCE6         =         236;
        public const int WAR_AMBIENCE7         =         237;
        public const int WAR_AMBIENCE8         =         238;
        public const int WAR_AMBIENCE9         =         239;
        public const int WAR_AMBIENCE10        =         240;
        public const int ALIEN_TALK1           =         241;
        public const int ALIEN_TALK2           =         242;
        public const int EXITMENUSOUND         =         243;
        public const int FLY_BY                =         244;
        public const int DUKE_SCREAM           =         245;
        public const int SHRINKER_HIT          =         246;
        public const int RATTY                 =         247;
        public const int INTO_MENU             =         248;
        public const int BONUSMUSIC            =         249;
        public const int DUKE_BOOBY            =         250;
        public const int DUKE_TALKTOBOSSFALL   =         251;
        public const int DUKE_LOOKINTOMIRROR   =         252;
        public const int PIG_ROAM3             =         253;
        public const int KILLME                =         254;
        public const int DRON_JETSND           =         255;
        public const int SPACE_DOOR1           =         256;
        public const int SPACE_DOOR2           =         257;
        public const int SPACE_DOOR3           =         258;
        public const int SPACE_DOOR4           =         259;
        public const int SPACE_DOOR5           =         260;
        public const int ALIEN_ELEVATOR1       =         261;
        public const int VAULT_DOOR            =         262;
        public const int JIBBED_ACTOR13        =         263;
        public const int DUKE_GETWEAPON6       =         264;
        public const int JIBBED_ACTOR8         =         265;
        public const int JIBBED_ACTOR9         =         266;
        public const int JIBBED_ACTOR10        =         267;
        public const int JIBBED_ACTOR11        =         268;
        public const int JIBBED_ACTOR12        =         269;
        public const int DUKE_KILLED4          =         270;
        public const int DUKE_KILLED5          =         271;
        public const int ALIEN_SWITCH1         =         272;
        public const int DUKE_STEPONFECES      =         273;
        public const int DUKE_LONGTERM_PAIN2   =         274;
        public const int DUKE_LONGTERM_PAIN3   =         275;
        public const int DUKE_LONGTERM_PAIN4   =         276;
        public const int COMPANB2              =         277;
        public const int KTIT                  =         278;
        public const int HELICOP_IDLE          =         279;
        public const int STEPNIT               =         280;
        public const int SPACE_AMBIENCE1       =         281;
        public const int SPACE_AMBIENCE2       =         282;
        public const int SLIM_HATCH            =         283;
        public const int RIPHEADNECK           =         284;
        public const int FOUNDJONES            =         285;
        public const int ALIEN_DOOR1           =         286;
        public const int ALIEN_DOOR2           =         287;
        public const int ENDSEQVOL3SND4        =         288;
        public const int ENDSEQVOL3SND5        =         289;
        public const int ENDSEQVOL3SND6        =         290;
        public const int ENDSEQVOL3SND7        =         291;
        public const int ENDSEQVOL3SND8        =         292;
        public const int ENDSEQVOL3SND9        =         293;
        public const int WHIPYOURASS           =         294;
        public const int ENDSEQVOL2SND1        =         295;
        public const int ENDSEQVOL2SND2        =         296;
        public const int ENDSEQVOL2SND3        =         297;
        public const int ENDSEQVOL2SND4        =         298;
        public const int ENDSEQVOL2SND5        =         299;
        public const int ENDSEQVOL2SND6        =         300;
        public const int ENDSEQVOL2SND7        =         301;
        public const int GENERIC_AMBIENCE23    =         302;
        public const int SOMETHINGFROZE        =         303;
        public const int DUKE_LONGTERM_PAIN5   =         304;
        public const int DUKE_LONGTERM_PAIN6   =         305;
        public const int DUKE_LONGTERM_PAIN7   =         306;
        public const int DUKE_LONGTERM_PAIN8   =         307;
        public const int WIND_REPEAT           =         308;
        public const int MYENEMY_ROAM          =         309;
        public const int MYENEMY_HURT          =         310;
        public const int MYENEMY_DEAD          =         311;
        public const int MYENEMY_SHOOT         =         312;
        public const int STORE_MUSIC           =         313;
        public const int STORE_MUSIC_BROKE     =         314;
        public const int ACTOR_GROWING         =         315;
        public const int NEWBEAST_ROAM         =         316;
        public const int NEWBEAST_RECOG        =         317;
        public const int NEWBEAST_ATTACK       =         318;
        public const int NEWBEAST_PAIN         =         319;
        public const int NEWBEAST_DYING        =         320;
        public const int NEWBEAST_SPIT         =         321;
        public const int VOL4_1                =         322;
        public const int SUPERMARKET           =         323;
        public const int MOUSEANNOY            =         324;
        public const int BOOKEM                =         325;
        public const int SUPERMARKETCRY        =         326;
        public const int DESTRUCT              =         327;
        public const int EATFOOD               =         328;
        public const int MAKEMYDAY             =         329;
        public const int WITNESSSTAND          =         330;
        public const int VACATIONSPEECH        =         331;
        public const int YIPPEE1               =         332;
        public const int YOHOO1                =         333;
        public const int YOHOO2                =         334;
        public const int DOLPHINSND            =         335;
        public const int TOUGHGALSND1          =         336;
        public const int TOUGHGALSND2          =         337;
        public const int TOUGHGALSND3          =         338;
        public const int TOUGHGALSND4          =         339;
        public const int TANK_ROAM             =         340;
        public const int BOS4_ROAM             =         341;
        public const int BOS4_RECOG            =         342;
        public const int BOS4_ATTACK           =         343;
        public const int BOS4_PAIN             =         344;
        public const int BOS4_DYING            =         345;
        public const int NEWBEAST_ATTACKMISS   =         346;
        public const int VOL4_2                =         347;
        public const int COOKINGDEEPFRIER      =         348;
        public const int WHINING_DOG           =         349;
        public const int DEAD_DOG              =         350;
        public const int LIGHTNING_SLAP        =         351;
        public const int THUNDER               =         352;
        public const int HAPPYMOUSESND1        =         353;
        public const int HAPPYMOUSESND2        =         354;
        public const int HAPPYMOUSESND3        =         355;
        public const int HAPPYMOUSESND4        =         356;
        public const int ALARM                 =         357;
        public const int RAIN                  =         358;
        public const int DTAG_GREENRUN         =         359;
        public const int DTAG_BROWNRUN         =         360;
        public const int DTAG_GREENSCORE       =         361;
        public const int DTAG_BROWNSCORE       =         362;
        public const int INTRO4_1              =         363;
        public const int INTRO4_2              =         364;
        public const int INTRO4_3              =         365;
        public const int INTRO4_4              =         366;
        public const int INTRO4_5              =         367;
        public const int INTRO4_6              =         368;
        public const int SCREECH               =         369;
        public const int BOSS4_DEADSPEECH      =         370;
        public const int BOSS4_FIRSTSEE        =         371;
        public const int PARTY_SPEECH          =         372;
        public const int POSTAL_SPEECH         =         373;
        public const int TGSPEECH              =         374;
        public const int DOGROOMSPEECH         =         375;
        public const int SMACKED               =         376;
        public const int MDEVSPEECH            =         377;
        public const int AREA51SPEECH          =         378;
        public const int JEEPSOUND             =         379;
        public const int BIGDOORSLAM           =         380;
        public const int BOS4_LAY              =         381;
        public const int WAVESOUND             =         382;
        public const int ILLBEBACK             =         383;
        public const int VOL4ENDSND1           =         384;
        public const int VOL4ENDSND2           =         385;
        public const int EXPANDERHIT           =         386;
        public const int SNAKESPEECH           =         387;
        public const int EXPANDERSHOOT         =         388;
        public const int GETBACKTOWORK         =         389;
        public const int JIBBED_ACTOR14        =         390;
        public const int JIBBED_ACTOR15        =         391;
        public const int INTRO4_B              =         392;
        public const int BIGBANG               =         393;
        public const int SMACKIT               =         394;
        public const int BELLSND = 395;
    }
}