//-------------------------------------------------------------------------
/*
Copyright (c) 2010 - JV Software
Copyright (C) 1996, 2003 - 3D Realms Entertainment

This file is part of the XNA Duke Nukem 3D Atomic Edition Port

Duke Nukem 3D is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
ashort with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Original Source: 1996 - Todd Replogle
Prepared for public release: 03/21/2003 - Charlie Wiederhold, 3D Realms
Ported to Silverlight/XNA C# 05/03/2011 - Justin Marshall, JV Software
*/
//-------------------------------------------------------------------------

using System;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;

namespace duke3d.game
{
    public static class SoundId
    {
        public static short KICK_HIT              =           0;
        public static short PISTOL_RICOCHET       =           1;
        public static short PISTOL_BODYHIT        =           2;
        public static short PISTOL_FIRE           =           3;
        public static short EJECT_CLIP            =           4;
        public static short INSERT_CLIP           =           5;
        public static short CHAINGUN_FIRE         =           6;
        public static short RPG_SHOOT             =           7;
        public static short POOLBALLHIT           =           8;
        public static short RPG_EXPLODE           =           9;
        public static short CAT_FIRE              =          10;
        public static short SHRINKER_FIRE         =          11;
        public static short ACTOR_SHRINKING       =          12;
        public static short PIPEBOMB_BOUNCE       =          13;
        public static short PIPEBOMB_EXPLODE      =          14;
        public static short LASERTRIP_ONWALL      =          15;
        public static short LASERTRIP_ARMING      =          16;
        public static short LASERTRIP_EXPLODE     =          17;
        public static short VENT_BUST             =          18;
        public static short GLASS_BREAKING        =          19;
        public static short GLASS_HEAVYBREAK      =          20;
        public static short SHORT_CIRCUIT         =          21;
        public static short ITEM_SPLASH           =          22;
        public static short DUKE_BREATHING        =          23;
        public static short DUKE_EXHALING         =          24;
        public static short DUKE_GASP             =          25;
        public static short SLIM_RECOG            =          26;
        // public static short ENDSEQVOL3SND1     =             27;
        public static short DUKE_URINATE          =          28;
        public static short ENDSEQVOL3SND2        =          29;
        public static short ENDSEQVOL3SND3        =          30;
        public static short DUKE_PASSWIND         =          32;
        public static short DUKE_CRACK            =          33;
        public static short SLIM_ATTACK           =          34;
        public static short SOMETHINGHITFORCE     =          35;
        public static short DUKE_DRINKING         =          36;
        public static short DUKE_KILLED1          =          37;
        public static short DUKE_GRUNT            =          38;
        public static short DUKE_HARTBEAT         =          39;
        public static short DUKE_ONWATER          =          40;
        public static short DUKE_DEAD             =          41;
        public static short DUKE_LAND             =          42;
        public static short DUKE_WALKINDUCTS      =          43;
        public static short DUKE_GLAD             =          44;
        public static short DUKE_YES              =          45;
        public static short DUKE_HEHE             =          46;
        public static short DUKE_SHUCKS           =          47;
        public static short DUKE_UNDERWATER       =          48;
        public static short DUKE_JETPACK_ON       =          49;
        public static short DUKE_JETPACK_IDLE     =          50;
        public static short DUKE_JETPACK_OFF      =          51;
        public static short LIZTROOP_GROWL        =          52;
        public static short LIZTROOP_TALK1        =          53;
        public static short LIZTROOP_TALK2        =          54;
        public static short LIZTROOP_TALK3        =          55;
        public static short DUKETALKTOBOSS        =          56;
        public static short LIZCAPT_GROWL         =          57;
        public static short LIZCAPT_TALK1         =          58;
        public static short LIZCAPT_TALK2         =          59;
        public static short LIZCAPT_TALK3         =          60;
        public static short LIZARD_BEG            =          61;
        public static short LIZARD_PAIN           =          62;
        public static short LIZARD_DEATH          =          63;
        public static short LIZARD_SPIT           =          64;
        public static short DRONE1_HISSRATTLE     =          65;
        public static short DRONE1_HISSSCREECH    =          66;
        public static short DUKE_TIP2             =          67;
        public static short FLESH_BURNING         =          68;
        public static short SQUISHED              =          69;
        public static short TELEPORTER            =          70;
        public static short ELEVATOR_ON           =          71;
        public static short DUKE_KILLED3          =          72;
        public static short ELEVATOR_OFF          =          73;
        public static short DOOR_OPERATE1         =          74;
        public static short SUBWAY                =          75;
        public static short SWITCH_ON             =          76;
        public static short FAN                   =          77;
        public static short DUKE_GETWEAPON3       =          78;
        public static short FLUSH_TOILET          =          79;
        public static short HOVER_CRAFT           =          80;
        public static short EARTHQUAKE            =          81;
        public static short shortRUDER_ALERT        =          82;
        public static short END_OF_LEVEL_WARN     =          83;
        public static short ENGINE_OPERATING      =          84;
        public static short REACTOR_ON            =          85;
        public static short COMPUTER_AMBIENCE     =          86;
        public static short GEARS_GRINDING        =          87;
        public static short BUBBLE_AMBIENCE       =          88;
        public static short MACHINE_AMBIENCE      =          89;
        public static short SEWER_AMBIENCE        =          90;
        public static short WIND_AMBIENCE         =          91;
        public static short SOMETHING_DRIPPING    =          92;
        public static short STEAM_HISSING         =          93;
        public static short THEATER_BREATH        =          94;
        public static short BAR_MUSIC             =          95;
        public static short BOS1_ROAM             =          96;
        public static short BOS1_RECOG            =          97;
        public static short BOS1_ATTACK1          =          98;
        public static short BOS1_PAIN             =          99;
        public static short BOS1_DYING            =         100;
        public static short BOS2_ROAM             =         101;
        public static short BOS2_RECOG            =         102;
        public static short BOS2_ATTACK           =         103;
        public static short BOS2_PAIN             =         104;
        public static short BOS2_DYING            =         105;
        public static short GETATOMICHEALTH       =         106;
        public static short DUKE_GETWEAPON2       =         107;
        public static short BOS3_DYING            =         108;
        public static short SHOTGUN_FIRE          =         109;
        public static short PRED_ROAM             =         110;
        public static short PRED_RECOG            =         111;
        public static short PRED_ATTACK           =         112;
        public static short PRED_PAIN             =         113;
        public static short PRED_DYING            =         114;
        public static short CAPT_ROAM             =         115;
        public static short CAPT_ATTACK           =         116;
        public static short CAPT_RECOG            =         117;
        public static short CAPT_PAIN             =         118;
        public static short CAPT_DYING            =         119;
        public static short PIG_ROAM              =         120;
        public static short PIG_RECOG             =         121;
        public static short PIG_ATTACK            =         122;
        public static short PIG_PAIN              =         123;
        public static short PIG_DYING             =         124;
        public static short RECO_ROAM             =         125;
        public static short RECO_RECOG            =         126;
        public static short RECO_ATTACK           =         127;
        public static short RECO_PAIN             =         128;
        public static short RECO_DYING            =         129;
        public static short DRON_ROAM             =         130;
        public static short DRON_RECOG            =         131;
        public static short DRON_ATTACK1          =         132;
        public static short DRON_PAIN             =         133;
        public static short DRON_DYING            =         134;
        public static short COMM_ROAM             =         135;
        public static short COMM_RECOG            =         136;
        public static short COMM_ATTACK           =         137;
        public static short COMM_PAIN             =         138;
        public static short COMM_DYING            =         139;
        public static short OCTA_ROAM             =         140;
        public static short OCTA_RECOG            =         141;
        public static short OCTA_ATTACK1          =         142;
        public static short OCTA_PAIN             =         143;
        public static short OCTA_DYING            =         144;
        public static short TURR_ROAM             =         145;
        public static short TURR_RECOG            =         146;
        public static short TURR_ATTACK           =         147;
        public static short DUMPSTER_MOVE         =         148;
        public static short SLIM_DYING            =         149;
        public static short BOS3_ROAM             =         150;
        public static short BOS3_RECOG            =         151;
        public static short BOS3_ATTACK1          =         152;
        public static short BOS3_PAIN             =         153;
        public static short BOS1_ATTACK2          =         154;
        public static short COMM_SPIN             =         155;
        public static short BOS1_WALK             =         156;
        public static short DRON_ATTACK2          =         157;
        public static short THUD                  =         158;
        public static short OCTA_ATTACK2          =         159;
        public static short WIERDSHOT_FLY         =         160;
        public static short TURR_PAIN             =         161;
        public static short TURR_DYING            =         162;
        public static short SLIM_ROAM             =         163;
        public static short LADY_SCREAM           =         164;
        public static short DOOR_OPERATE2         =         165;
        public static short DOOR_OPERATE3         =         166;
        public static short DOOR_OPERATE4         =         167;
        public static short BORNTOBEWILDSND       =         168;
        public static short SHOTGUN_COCK          =         169;
        public static short GENERIC_AMBIENCE1     =         170;
        public static short GENERIC_AMBIENCE2     =         171;
        public static short GENERIC_AMBIENCE3     =         172;
        public static short GENERIC_AMBIENCE4     =         173;
        public static short GENERIC_AMBIENCE5     =         174;
        public static short GENERIC_AMBIENCE6     =         175;
        public static short BOS3_ATTACK2          =         176;
        public static short GENERIC_AMBIENCE17    =         177;
        public static short GENERIC_AMBIENCE18    =         178;
        public static short GENERIC_AMBIENCE19    =         179;
        public static short GENERIC_AMBIENCE20    =         180;
        public static short GENERIC_AMBIENCE21    =         181;
        public static short GENERIC_AMBIENCE22    =         182;
        public static short SECRETLEVELSND        =         183;
        public static short GENERIC_AMBIENCE8     =         184;
        public static short GENERIC_AMBIENCE9     =         185;
        public static short GENERIC_AMBIENCE10    =         186;
        public static short GENERIC_AMBIENCE11    =         187;
        public static short GENERIC_AMBIENCE12    =         188;
        public static short GENERIC_AMBIENCE13    =         189;
        public static short GENERIC_AMBIENCE14    =         190;
        public static short GENERIC_AMBIENCE15    =         192;
        public static short GENERIC_AMBIENCE16    =         193;
        public static short FIRE_CRACKLE          =         194;
        public static short BONUS_SPEECH1         =         195;
        public static short BONUS_SPEECH2         =         196;
        public static short BONUS_SPEECH3         =         197;
        public static short PIG_CAPTURE_DUKE      =         198;
        public static short BONUS_SPEECH4         =         199;
        public static short DUKE_LAND_HURT        =         200;
        public static short DUKE_HIT_STRIPPER1    =         201;
        public static short DUKE_TIP1             =         202;
        public static short DUKE_KILLED2          =         203;
        public static short PRED_ROAM2            =         204;
        public static short PIG_ROAM2             =         205;
        public static short DUKE_GETWEAPON1       =         206;
        public static short DUKE_SEARCH2          =         207;
        public static short DUKE_CRACK2           =         208;
        public static short DUKE_SEARCH           =         209;
        public static short DUKE_GET              =         210;
        public static short DUKE_LONGTERM_PAIN    =         211;
        public static short MONITOR_ACTIVE        =         212;
        public static short NITEVISION_ONOFF      =         213;
        public static short DUKE_HIT_STRIPPER2    =         214;
        public static short DUKE_CRACK_FIRST      =         215;
        public static short DUKE_USEMEDKIT        =         216;
        public static short DUKE_TAKEPILLS        =         217;
        public static short DUKE_PISSRELIEF       =         218;
        public static short SELECT_WEAPON         =         219;
        public static short WATER_GURGLE          =         220;
        public static short DUKE_GETWEAPON4       =         221;
        public static short JIBBED_ACTOR1         =         222;
        public static short JIBBED_ACTOR2         =         223;
        public static short JIBBED_ACTOR3         =         224;
        public static short JIBBED_ACTOR4         =         225;
        public static short JIBBED_ACTOR5         =         226;
        public static short JIBBED_ACTOR6         =         227;
        public static short JIBBED_ACTOR7         =         228;
        public static short DUKE_GOTHEALTHATLOW   =         229;
        public static short BOSSTALKTODUKE        =         230;
        public static short WAR_AMBIENCE1         =         231;
        public static short WAR_AMBIENCE2         =         232;
        public static short WAR_AMBIENCE3         =         233;
        public static short WAR_AMBIENCE4         =         234;
        public static short WAR_AMBIENCE5         =         235;
        public static short WAR_AMBIENCE6         =         236;
        public static short WAR_AMBIENCE7         =         237;
        public static short WAR_AMBIENCE8         =         238;
        public static short WAR_AMBIENCE9         =         239;
        public static short WAR_AMBIENCE10        =         240;
        public static short ALIEN_TALK1           =         241;
        public static short ALIEN_TALK2           =         242;
        public static short EXITMENUSOUND         =         243;
        public static short FLY_BY                =         244;
        public static short DUKE_SCREAM           =         245;
        public static short SHRINKER_HIT          =         246;
        public static short RATTY                 =         247;
        public static short shortO_MENU             =         248;
        public static short BONUSMUSIC            =         249;
        public static short DUKE_BOOBY            =         250;
        public static short DUKE_TALKTOBOSSFALL   =         251;
        public static short DUKE_LOOKshortOMIRROR   =         252;
        public static short PIG_ROAM3             =         253;
        public static short KILLME                =         254;
        public static short DRON_JETSND           =         255;
        public static short SPACE_DOOR1           =         256;
        public static short SPACE_DOOR2           =         257;
        public static short SPACE_DOOR3           =         258;
        public static short SPACE_DOOR4           =         259;
        public static short SPACE_DOOR5           =         260;
        public static short ALIEN_ELEVATOR1       =         261;
        public static short VAULT_DOOR            =         262;
        public static short JIBBED_ACTOR13        =         263;
        public static short DUKE_GETWEAPON6       =         264;
        public static short JIBBED_ACTOR8         =         265;
        public static short JIBBED_ACTOR9         =         266;
        public static short JIBBED_ACTOR10        =         267;
        public static short JIBBED_ACTOR11        =         268;
        public static short JIBBED_ACTOR12        =         269;
        public static short DUKE_KILLED4          =         270;
        public static short DUKE_KILLED5          =         271;
        public static short ALIEN_SWITCH1         =         272;
        public static short DUKE_STEPONFECES      =         273;
        public static short DUKE_LONGTERM_PAIN2   =         274;
        public static short DUKE_LONGTERM_PAIN3   =         275;
        public static short DUKE_LONGTERM_PAIN4   =         276;
        public static short COMPANB2              =         277;
        public static short KTIT                  =         278;
        public static short HELICOP_IDLE          =         279;
        public static short STEPNIT               =         280;
        public static short SPACE_AMBIENCE1       =         281;
        public static short SPACE_AMBIENCE2       =         282;
        public static short SLIM_HATCH            =         283;
        public static short RIPHEADNECK           =         284;
        public static short FOUNDJONES            =         285;
        public static short ALIEN_DOOR1           =         286;
        public static short ALIEN_DOOR2           =         287;
        public static short ENDSEQVOL3SND4        =         288;
        public static short ENDSEQVOL3SND5        =         289;
        public static short ENDSEQVOL3SND6        =         290;
        public static short ENDSEQVOL3SND7        =         291;
        public static short ENDSEQVOL3SND8        =         292;
        public static short ENDSEQVOL3SND9        =         293;
        public static short WHIPYOURASS           =         294;
        public static short ENDSEQVOL2SND1        =         295;
        public static short ENDSEQVOL2SND2        =         296;
        public static short ENDSEQVOL2SND3        =         297;
        public static short ENDSEQVOL2SND4        =         298;
        public static short ENDSEQVOL2SND5        =         299;
        public static short ENDSEQVOL2SND6        =         300;
        public static short ENDSEQVOL2SND7        =         301;
        public static short GENERIC_AMBIENCE23    =         302;
        public static short SOMETHINGFROZE        =         303;
        public static short DUKE_LONGTERM_PAIN5   =         304;
        public static short DUKE_LONGTERM_PAIN6   =         305;
        public static short DUKE_LONGTERM_PAIN7   =         306;
        public static short DUKE_LONGTERM_PAIN8   =         307;
        public static short WIND_REPEAT           =         308;
        public static short MYENEMY_ROAM          =         309;
        public static short MYENEMY_HURT          =         310;
        public static short MYENEMY_DEAD          =         311;
        public static short MYENEMY_SHOOT         =         312;
        public static short STORE_MUSIC           =         313;
        public static short STORE_MUSIC_BROKE     =         314;
        public static short ACTOR_GROWING         =         315;
        public static short NEWBEAST_ROAM         =         316;
        public static short NEWBEAST_RECOG        =         317;
        public static short NEWBEAST_ATTACK       =         318;
        public static short NEWBEAST_PAIN         =         319;
        public static short NEWBEAST_DYING        =         320;
        public static short NEWBEAST_SPIT         =         321;
        public static short VOL4_1                =         322;
        public static short SUPERMARKET           =         323;
        public static short MOUSEANNOY            =         324;
        public static short BOOKEM                =         325;
        public static short SUPERMARKETCRY        =         326;
        public static short DESTRUCT              =         327;
        public static short EATFOOD               =         328;
        public static short MAKEMYDAY             =         329;
        public static short WITNESSSTAND          =         330;
        public static short VACATIONSPEECH        =         331;
        public static short YIPPEE1               =         332;
        public static short YOHOO1                =         333;
        public static short YOHOO2                =         334;
        public static short DOLPHINSND            =         335;
        public static short TOUGHGALSND1          =         336;
        public static short TOUGHGALSND2          =         337;
        public static short TOUGHGALSND3          =         338;
        public static short TOUGHGALSND4          =         339;
        public static short TANK_ROAM             =         340;
        public static short BOS4_ROAM             =         341;
        public static short BOS4_RECOG            =         342;
        public static short BOS4_ATTACK           =         343;
        public static short BOS4_PAIN             =         344;
        public static short BOS4_DYING            =         345;
        public static short NEWBEAST_ATTACKMISS   =         346;
        public static short VOL4_2                =         347;
        public static short COOKINGDEEPFRIER      =         348;
        public static short WHINING_DOG           =         349;
        public static short DEAD_DOG              =         350;
        public static short LIGHTNING_SLAP        =         351;
        public static short THUNDER               =         352;
        public static short HAPPYMOUSESND1        =         353;
        public static short HAPPYMOUSESND2        =         354;
        public static short HAPPYMOUSESND3        =         355;
        public static short HAPPYMOUSESND4        =         356;
        public static short ALARM                 =         357;
        public static short RAIN                  =         358;
        public static short DTAG_GREENRUN         =         359;
        public static short DTAG_BROWNRUN         =         360;
        public static short DTAG_GREENSCORE       =         361;
        public static short DTAG_BROWNSCORE       =         362;
        public static short shortRO4_1              =         363;
        public static short shortRO4_2              =         364;
        public static short shortRO4_3              =         365;
        public static short shortRO4_4              =         366;
        public static short shortRO4_5              =         367;
        public static short shortRO4_6              =         368;
        public static short SCREECH               =         369;
        public static short BOSS4_DEADSPEECH      =         370;
        public static short BOSS4_FIRSTSEE        =         371;
        public static short PARTY_SPEECH          =         372;
        public static short POSTAL_SPEECH         =         373;
        public static short TGSPEECH              =         374;
        public static short DOGROOMSPEECH         =         375;
        public static short SMACKED               =         376;
        public static short MDEVSPEECH            =         377;
        public static short AREA51SPEECH          =         378;
        public static short JEEPSOUND             =         379;
        public static short BIGDOORSLAM           =         380;
        public static short BOS4_LAY              =         381;
        public static short WAVESOUND             =         382;
        public static short ILLBEBACK             =         383;
        public static short VOL4ENDSND1           =         384;
        public static short VOL4ENDSND2           =         385;
        public static short EXPANDERHIT           =         386;
        public static short SNAKESPEECH           =         387;
        public static short EXPANDERSHOOT         =         388;
        public static short GETBACKTOWORK         =         389;
        public static short JIBBED_ACTOR14        =         390;
        public static short JIBBED_ACTOR15        =         391;
        public static short shortRO4_B              =         392;
        public static short BIGBANG               =         393;
        public static short SMACKIT               =         394;
        public static short BELLSND = 395;
    }
}